name = "decardy-website"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# If you want to bind to your real domain:
# routes = [
#   { pattern = "decardy.com/*", zone_name = "decardy.com" }
# ]

[assets]
directory = "./dist"
binding = "ASSETS"
